# -*- coding: utf-8 -*-
"""example_table_evaluator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJC9-y16W3JQ2oeDXRrp4Vs19QlnrqK7

# Example Notebook: How to analyse synthetic data
This notebook will show, fairly compact, how to analyse the data that you have someone obtained.
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext autoreload
# %autoreload 2

from table_evaluator import TableEvaluator, load_data

real, fake = load_data('data/real_test_sample.csv', 'data/fake_test_sample.csv')

real.head()

fake.head()

cat_cols = ['trans_type', 'trans_operation', 'trans_k_symbol']

evaluator = TableEvaluator(real, fake, cat_cols=cat_cols)

"""### We can do a numerical analysis"""

evaluator.evaluate(target_col='trans_type', notebook=False, verbose=False)

"""### But we can also do a visual analysis"""

evaluator.visual_evaluation()